#!/opt/optiplex-lab/venv/bin/python
from __future__ import annotations
import hashlib,json,pathlib
from datetime import datetime,timezone

BENCH=pathlib.Path('/var/lib/optiplex-lab/benchmarks/gen6-experience-memory-benchmark.json')
OUT=pathlib.Path('/var/lib/optiplex-lab/benchmarks/gen7-proposals.json')

def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest() if p.exists() else None

def main():
 b=json.loads(BENCH.read_text()); m=b['metrics']; ctx=m['context_packet_proxy']; ft=m['failure_to_regression']; md=m['memory_distillation']; lat=m['memory_retrieval_latency_ms']
 proposals=[]
 def add(title,kind,evidence,benefit,complexity): proposals.append({'rank':len(proposals)+1,'title':title,'kind':kind,'evidence':evidence,'expected_benefit':benefit,'complexity':complexity})
 add('Architectural Digital Twin + Causal Observability Spine','self-model/observability',f"Gen6 memory retrieval reached {m['correct_memory_retrieval_rate']:.0%} correct retrieval and {m['wrong_memory_invocation_rate']:.0%} wrong-memory invocation at median {lat['median']} ms, so procedure selection is no longer the dominant measured gap. Failure compilation produced {ft['active_conversions']} active capability regression but also {ft['candidate_uncertain']} uncertainty-retained regression; the compiler explicitly cannot claim causal minimality. A provenance-backed architecture/dependency model plus parent/child causal spans would improve impact analysis and failure attribution without replacing source authority.",'Make the Lab queryably understand component→capability→workflow→evaluator→regression→runtime dependencies and provide better causal evidence for future regression synthesis. Keep all model facts derived and hash-linked to authoritative artifacts.','medium')
 add('Context Compiler on top of the Digital Twin','context/retrieval',f"Gen6 already reduced the measured repeated-task selection-context proxy from {ctx['no_memory_active_capability_registry_bytes']} B to {ctx['with_memory_selected_packet_bytes']} B ({ctx['reduction']:.1%}) using procedural memory alone. That is strong evidence to avoid building a context system first; once an architectural twin exists, a compiler can extend the same progressive-disclosure principle to source/invariants/history without reloading the whole repository.",'Compile bounded task-specific context packets containing mandatory containment invariants, relevant architecture, memories, regressions, and exact source pointers, with freshness/hash checks.','medium')
 add('Evaluator / Mutation Nursery','verification',f"An intentionally weak later evaluator passed its local cases, while the automatically generated regression caught the bad descendant; accepted-known-good false-positive rate was {ft['accepted_known_good_false_positive_rate']:.0%}. This shows regression replay works, but also that evaluator breadth remains a source of candidate risk.",'Generate bounded mutants/property/adversarial cases and test evaluator discrimination before promotion, using regression lineage as seed evidence.','medium')
 add('Capability Consolidator with semantic lineage','retention',f"Gen6 demonstrated active memory supersession/retirement and ended with {md['registry_total']} memory records ({md['active']} active, {md['retired']} retired, {md['candidate_rejection_or_hold']} held candidate). Registry growth is currently controlled, so semantic consolidation is useful but not yet the top bottleneck.",'Consolidate near-equivalent capability/memory lineages while replaying all attached evaluators/regressions and preserving immutable ancestry.','low-medium')
 add('Counterfactual Replay','replay',f"Gen6 could replay immutable capability I/O failures and command-exit failures, but timeout conversion remained uncertainty-gated without a known-good reference. Historical replay fidelity would make more failures safely promotable as regressions.",'Reconstruct replayable historical episodes in disposable workspaces and swap one capability/evaluator version at a time with explicit replay-fidelity labels.','large')
 out={'generated_at':datetime.now(timezone.utc).isoformat(),'generation':'gen7-proposals-from-gen6-evidence','implemented':False,'source_benchmark':str(BENCH),'source_benchmark_sha256':sha(BENCH),'headline_question':'What remains after successful and failed experience now compounds into inspectable procedural memory and regressions?','gen6_metrics':m,'top_recommendation':proposals[0]['title'],'roadmap_assessment':'The existing Gen7 direction remains broadly correct, but Gen6 evidence changes the ordering: build the provenance-backed Architectural Digital Twin together with richer causal observability first; layer the Context Compiler on top because procedural memory already delivered substantial context reduction for repeated tasks.','proposals':proposals}
 OUT.parent.mkdir(parents=True,exist_ok=True); OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n'); print(json.dumps(out,indent=2,sort_keys=True))
if __name__=='__main__': main()
